name: Build c++11

on: [push, pull_request]

jobs:

  MIN-GW:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
    - uses: actions/checkout@v2.4.2
    - name: Create Compile Folder
      run: |
        &mkdir ./compile
    - name: Setup MinGW
      id: setup
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
        cc: 1
    - name : Check version
      run: |
        & '${{ steps.setup.outputs.gxx }}' --version
    - name: Setting Date Variable
      id: date
      run: echo "::set-output name=today::$(date +'%d%m%y-%H%M%S')"
    - name : Build main.cpp
      run: |
       & '${{ steps.setup.outputs.gxx }}' -Wall -Wextra -o ./compile/result_${{ steps.date.outputs.today }} ./src/main.cpp -std=c++11 -static
    - name : Upload Artifact 
      uses : actions/upload-artifact@v3.1.0
      with:
          name: FP_${{ steps.date.outputs.today }}
          path: ./compile/
          retention-days: 2
